/**
 * Phase 16D Stage A — six-digit memorable access-PIN generator (DARK).
 *
 * Pure, server-only. Draws candidates from a cryptographically secure source
 * (crypto.randomInt), rejects weak/guessable/context-derived candidates, and
 * keeps only codes with SOME memorability feature — without forcing every
 * code into one recognizable template (varied features, modest threshold, so
 * the accepted pool stays in the hundreds of thousands).
 *
 * LEADING ZERO IS REJECTED, deliberately: the loading workflow is a human
 * manually copying the PIN into two different Aqara apps/keypads (A100
 * scheduled PIN; U100 scheduled user + PIN). Any numeric intermediate — a
 * spreadsheet cell, a numeric form field, a person reading "082415" aloud as
 * "82415" — silently drops the zero and desynchronizes the magazine from the
 * locks, and this task cannot verify that both lock workflows preserve it.
 * The 900,000-candidate pool minus rejections is still enormous headroom for
 * a 140-credential magazine.
 *
 * No real production PIN is generated by importing this module; generation
 * happens only when a later approved stage calls it.
 */

import { randomInt } from "crypto";

export const ACCESS_PIN_MAX_ATTEMPTS_DEFAULT = 1000;

/** Thrown when the bounded attempt budget is exhausted — never loops forever. */
export class AccessPinGenerationExhaustedError extends Error {
  constructor(attempts: number) {
    super(`[access-pin-generator] no acceptable PIN after ${attempts} attempts`);
    this.name = "AccessPinGenerationExhaustedError";
  }
}

export interface AccessPinGenerationContext {
  /**
   * Digit strings the PIN must not resemble: guest/property phone numbers,
   * booking-reference digits, property street numbers, relevant dates.
   * Non-digits are stripped; every 4-digit window of each value is forbidden
   * as a substring of the PIN.
   */
  forbiddenDigitStrings?: readonly string[];
  /**
   * Keyed fingerprints of every current AND historical credential
   * (access_credentials.pin_fingerprint — retained even after destruction),
   * plus a function that fingerprints a candidate under EVERY retained
   * fingerprint-key version (lib/access/pin-vault.ts
   * fingerprintAccessPinAllKeys). A candidate is rejected when ANY of its
   * per-key fingerprints is already present, so duplicate detection survives
   * fingerprint-key rotation and a destroyed PIN can never be issued again.
   */
  existingFingerprints?: ReadonlySet<string>;
  fingerprints?: (pin: string) => readonly string[];
}

export type AccessPinRejectionReason =
  | "format"
  | "leading_zero"
  | "repeated_digit_run"
  | "digit_overuse"
  | "sequential_run"
  | "repeated_half"
  | "alternating_pair"
  | "palindrome"
  | "common_pin"
  | "keypad_line"
  | "year_pattern"
  | "date_pattern"
  | "context_digits"
  | "already_used";

/**
 * Widely used six-digit PINs from published breach-frequency analyses that
 * the structural rules alone would not all catch. Extensible; order is
 * irrelevant. (Most classics — 123456, 111111, 123123, 121212 — are already
 * structurally rejected; they are listed anyway so the policy is explicit.)
 */
const COMMON_PINS = new Set([
  "123456", "654321", "111111", "000000", "123123", "666666", "121212",
  "112233", "789456", "159753", "222222", "999999", "888888", "777777",
  "555555", "333333", "444444", "101010", "202020", "131313", "141414",
  "123321", "456789", "987654", "696969", "159357", "147258", "258369",
  "741852", "852963", "963852", "456123", "321654", "147852", "369258",
  "123654", "100200", "520520", "110110", "786786", "112211", "221122",
  "159951", "753357", "246810", "135790",
]);

/** Phone-keypad rows, columns, and diagonals plus their reverses. */
const KEYPAD_TRIPLES = new Set([
  "123", "456", "789", "147", "258", "369", "159", "357",
  "321", "654", "987", "741", "852", "963", "951", "753",
]);

function longestSameDigitRun(pin: string): number {
  let longest = 1;
  let current = 1;
  for (let i = 1; i < pin.length; i++) {
    current = pin[i] === pin[i - 1] ? current + 1 : 1;
    if (current > longest) longest = current;
  }
  return longest;
}

function maxDigitCount(pin: string): number {
  const counts = new Map<string, number>();
  for (const digit of pin) counts.set(digit, (counts.get(digit) ?? 0) + 1);
  return Math.max(...counts.values());
}

function longestSequentialRun(pin: string): number {
  let longest = 1;
  for (const step of [1, -1]) {
    let current = 1;
    for (let i = 1; i < pin.length; i++) {
      current = Number(pin[i]) - Number(pin[i - 1]) === step ? current + 1 : 1;
      if (current > longest) longest = current;
    }
  }
  return longest;
}

function isPlausibleDayMonth(day: string, month: string): boolean {
  const d = Number(day);
  const m = Number(month);
  return d >= 1 && d <= 31 && m >= 1 && m <= 12;
}

function contextWindows(values: readonly string[]): Set<string> {
  const windows = new Set<string>();
  for (const value of values) {
    const digits = value.replace(/[^0-9]/g, "");
    for (let i = 0; i + 4 <= digits.length; i++) {
      windows.add(digits.slice(i, i + 4));
    }
  }
  return windows;
}

/**
 * Returns the first rejection reason for a candidate, or null if acceptable.
 * Exported separately so every rejection family is deterministically
 * unit-testable without touching the random source.
 */
export function rejectAccessPin(
  pin: string,
  context: AccessPinGenerationContext = {}
): AccessPinRejectionReason | null {
  if (!/^[0-9]{6}$/.test(pin)) return "format";
  if (pin[0] === "0") return "leading_zero";
  // Overuse (>=5 of one digit) is checked before the run rule so it is
  // reachable; four occurrences without a 3-run (e.g. the memorable
  // 25-56-55 shape) are deliberately acceptable.
  if (maxDigitCount(pin) >= 5) return "digit_overuse";
  if (longestSameDigitRun(pin) >= 3) return "repeated_digit_run";
  if (longestSequentialRun(pin) >= 4) return "sequential_run";
  if (pin.slice(0, 3) === pin.slice(3)) return "repeated_half";
  if (pin[0] === pin[2] && pin[2] === pin[4] && pin[1] === pin[3] && pin[3] === pin[5]) {
    return "alternating_pair";
  }
  if (pin === [...pin].reverse().join("")) return "palindrome";
  if (COMMON_PINS.has(pin)) return "common_pin";
  if (KEYPAD_TRIPLES.has(pin.slice(0, 3)) && KEYPAD_TRIPLES.has(pin.slice(3))) {
    return "keypad_line";
  }
  const head = Number(pin.slice(0, 4));
  const tail = Number(pin.slice(2));
  if ((head >= 1900 && head <= 2099) || (tail >= 1900 && tail <= 2099)) {
    return "year_pattern";
  }
  if (
    isPlausibleDayMonth(pin.slice(0, 2), pin.slice(2, 4)) || // DDMMYY
    isPlausibleDayMonth(pin.slice(2, 4), pin.slice(0, 2)) || // MMDDYY
    isPlausibleDayMonth(pin.slice(4, 6), pin.slice(2, 4))    // YYMMDD
  ) {
    return "date_pattern";
  }
  if (context.forbiddenDigitStrings?.length) {
    for (const window of contextWindows(context.forbiddenDigitStrings)) {
      if (pin.includes(window)) return "context_digits";
    }
  }
  if (context.existingFingerprints && context.fingerprints) {
    for (const candidateFingerprint of context.fingerprints(pin)) {
      if (context.existingFingerprints.has(candidateFingerprint)) return "already_used";
    }
  }
  return null;
}

/**
 * Memorability features, each independent — a candidate qualifies through
 * ANY {@link ACCESS_PIN_MEMORABILITY_THRESHOLD} of them, which is what keeps
 * the accepted shapes varied instead of one ABBCBB-style formula:
 *   1. a doubled adjacent pair somewhere ("25-56-55" reads easily);
 *   2. at most four distinct digits;
 *   3. digit span (max − min) of five or less — codes cluster on the keypad;
 *   4. one of the three spoken two-digit groups repeats;
 *   5. a group is "round" (ends in 0) or a doubled digit ("44").
 */
export const ACCESS_PIN_MEMORABILITY_THRESHOLD = 2;

export function scoreAccessPinMemorability(pin: string): number {
  let score = 0;
  if (/(\d)\1/.test(pin)) score += 1;
  if (new Set(pin).size <= 4) score += 1;
  const digits = [...pin].map(Number);
  if (Math.max(...digits) - Math.min(...digits) <= 5) score += 1;
  const groups = [pin.slice(0, 2), pin.slice(2, 4), pin.slice(4, 6)];
  if (groups[0] === groups[1] || groups[1] === groups[2] || groups[0] === groups[2]) score += 1;
  if (groups.some((group) => group[1] === "0" || group[0] === group[1])) score += 1;
  return score;
}

/**
 * Presentation-only grouping for reveal screens: "255655" -> "25-56-55".
 * Grouping happens at display time precisely so the generator does not have
 * to bake one visual pattern into the code itself.
 */
export function formatAccessPinForDisplay(pin: string): string {
  if (!/^[0-9]{6}$/.test(pin)) {
    throw new Error("[access-pin-generator] refusing to format: value is not a six-digit PIN");
  }
  return `${pin.slice(0, 2)}-${pin.slice(2, 4)}-${pin.slice(4, 6)}`;
}

/**
 * Draws candidates until one passes rejection + memorability, throwing
 * {@link AccessPinGenerationExhaustedError} at the bounded attempt budget.
 * The thrown error and all internals never contain candidate values.
 */
export function generateAccessPin(
  context: AccessPinGenerationContext = {},
  maxAttempts: number = ACCESS_PIN_MAX_ATTEMPTS_DEFAULT
): string {
  if (!Number.isInteger(maxAttempts) || maxAttempts <= 0) {
    throw new Error("[access-pin-generator] maxAttempts must be a positive integer");
  }
  for (let attempt = 0; attempt < maxAttempts; attempt++) {
    const pin = String(randomInt(100000, 1000000));
    if (rejectAccessPin(pin, context) !== null) continue;
    if (scoreAccessPinMemorability(pin) < ACCESS_PIN_MEMORABILITY_THRESHOLD) continue;
    return pin;
  }
  throw new AccessPinGenerationExhaustedError(maxAttempts);
}
